export default {
  data: {
    1010: {
      identifier: 1010,
      username: "Dan Auerbach",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing",
      created: "15 September 2021",
      prof_ico: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0A816QQ7i-w2DLwWBdY0nmq8-lHCUlcUHBw&usqp=CAU',
      is_read: true,
    },
    1011: {
      identifier: 1011,
      username: "Mia Brian",
      text: "sed do eiusmod tempor incididunt ut labore et dolore",
      created: "8 October 2021",
      prof_ico: 'https://i0.wp.com/worldbusinessfitness.com/wp-content/uploads/2018/06/opulent-profile-square-02.jpg',
      is_read: false,
    },
    1012: {
      identifier: 1012,
      username: "Emily Broemel",
      text: "minim veniam, quis nostrud exercitation",
      created: "20 October 2021",
      prof_ico: 'https://www.nzherald.co.nz/resizer/qsciwSumABgKMvLjKYvh2TK1sGs=/360x384/filters:quality(70)/arc-anglerfish-syd-prod-nzme.s3.amazonaws.com/public/QZI5SNWLCJANLBVQHUDCEQTNTE.jpg',
      is_read: false,
    },
    1013: {
      identifier: 1013,
      username: "Dan Auerbach",
      text: "Excepteur sint occaecat cupidatat non proident",
      created: "18 April 2012",
      prof_ico: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQGfF_3ycXBYHLIC4NWYcovKN8W_dsy98dqQw&usqp=CAU',
      is_read: true,
    },
    1014: {
      identifier: 1014,
      username: "Alex Lifeson",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing",
      created: "15 September 2021",
      prof_ico: 'https://uilove.in/realestate/listo/preview/img/demo/profile.jpg',
      is_read: false,
    },
    1015: {
      identifier: 1010,
      username: "Dan Auerbach",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing",
      created: "15 September 2021",
      prof_ico: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0A816QQ7i-w2DLwWBdY0nmq8-lHCUlcUHBw&usqp=CAU',
      is_read: true,
    },
    1016: {
      identifier: 1011,
      username: "Mia Brian",
      text: "sed do eiusmod tempor incididunt ut labore et dolore",
      created: "8 October 2021",
      prof_ico: 'https://i0.wp.com/worldbusinessfitness.com/wp-content/uploads/2018/06/opulent-profile-square-02.jpg',
      is_read: true,
    },
    1017: {
      identifier: 1012,
      username: "Carl Broemel",
      text: "minim veniam, quis nostrud exercitation",
      created: "20 October 2021",
      prof_ico: 'https://www.eventiz.biz/wp-content/uploads/2015/12/speaker-3.jpg',
      is_read: true,
    },
    1018: {
      identifier: 1013,
      username: "Dan Auerbach",
      text: "Excepteur sint occaecat cupidatat non proident",
      created: "18 April 2012",
      prof_ico: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQGfF_3ycXBYHLIC4NWYcovKN8W_dsy98dqQw&usqp=CAU',
      is_read: true,
    },
    1019: {
      identifier: 1014,
      username: "Alex Lifeson",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing",
      created: "15 September 2021",
      prof_ico: 'https://uilove.in/realestate/listo/preview/img/demo/profile.jpg',
      is_read: false,
    },
    1020: {
      identifier: 1010,
      username: "Dan Auerbach",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing",
      created: "15 September 2021",
      prof_ico: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0A816QQ7i-w2DLwWBdY0nmq8-lHCUlcUHBw&usqp=CAU',
      is_read: false,
    },
    1021: {
      identifier: 1011,
      username: "Mia Brian",
      text: "sed do eiusmod tempor incididunt ut labore et dolore",
      created: "8 October 2021",
      prof_ico: 'https://i0.wp.com/worldbusinessfitness.com/wp-content/uploads/2018/06/opulent-profile-square-02.jpg',
      is_read: true,
    },
    1022: {
      identifier: 1012,
      username: "Carl Broemel",
      text: "minim veniam, quis nostrud exercitation",
      created: "20 October 2021",
      prof_ico: 'https://www.eventiz.biz/wp-content/uploads/2015/12/speaker-3.jpg',
      is_read: true,
    },
    1023: {
      identifier: 1013,
      username: "Dan Auerbach",
      text: "Excepteur sint occaecat cupidatat non proident",
      created: "18 April 2012",
      prof_ico: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQGfF_3ycXBYHLIC4NWYcovKN8W_dsy98dqQw&usqp=CAU',
      is_read: true,
    },
    1024: {
      identifier: 1014,
      username: "Alex Lifeson",
      text: "Lorem ipsum dolor sit amet, consectetur adipiscing",
      created: "15 September 2021",
      prof_ico: 'https://uilove.in/realestate/listo/preview/img/demo/profile.jpg',
      is_read: true,
    },
  },
  success: true,
  unread_count: 5,
  total: 125,
  limit: 15,
};
