export const FETCH_NOTIFICATONS_LOADING = `FETCH_NOTIFICATONS_LOADING`;
export const FETCH_NOTIFICATONS_SUCCESS = `FETCH_NOTIFICATONS_SUCCESS`;
export const FETCH_NOTIFICATONS_ERROR = `FETCH_NOTIFICATONS_ERROR`;
